### ISSUE TITLE
Spectator mode can't noclip

### ISSUE THREAD

**Issue by ShayBox** [DaMatrix/Pork2b2tBot#11]
Self-explanatory, going in spectator mode doesn't tell the connecting clients that we can noclip into blocks.

EDIT: Also sub issue, I found this proxy that's a fork of this one that does not provide credit to the original, or provide the source code. http://killet.tk/maxprox/ (Breaking the license)

**Comment by maxtorcd55** [comment]
@ShayBox Can I ask you what this is on all the versions on the site? (see pic)

![pork](https://user-images.githubusercontent.com/17813646/43934789-49bc016c-9c51-11e8-94da-b28a73c5b624.png)

**Comment by DaMatrix** [comment]
Where did you download that? That looks like a modified version of my proxy

**Comment by maxtorcd55** [comment]
on that website, I just made changes so it work i can get the queue stats from it, a buildin autofish, ...
And yes, Its a modded version of yours, If you want me to get it offline let me know.

You can always contact me on discord (maxtorcd55#6063)
________________________________
Van: DaPorkchop_ <notifications@github.com>
Verzonden: vrijdag 10 augustus 2018 18:10:59
Aan: DaMatrix/Pork2b2tBot
CC: maxtorcd55; Comment
Onderwerp: Re: [DaMatrix/Pork2b2tBot] Spectator mode can't noclip (#11)


Where did you download that? That looks like a modified version of my proxy

**Comment by DaMatrix** [comment]
this is fixed in the newest post-rewrite versions.
