### ISSUE TITLE
Error dependencies

### ISSUE THREAD

**Issue by Votsh64** [DaMatrix/Pork2b2tBot#13]
[ERROR] Failed to execute goal on project mcprotocollib: Could not resolve dependencies for project com.github.steveice10:mcprotocollib:jar:1.13.2-1-SNAPSHOT: Failed to collect dependencies at com.github.steveice10:opennbt:jar:1.1: Failed to read artifact descriptor for com.github.steveice10:opennbt:jar:1.1: Could not transfer artifact com.github.steveice10:opennbt:pom:1.1 from/to jitpack.io (https://jitpack.io): java.security.ProviderException: java.security.InvalidKeyException: EC parameters error: no such provider: SunEC -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by DaMatrix** [comment]
that's not an issue on my end, that's an issue with either maven or java using the wrong keystore. what java version are you using?

**Comment by DaMatrix** [comment]
if you like i'll download and compile the correct versions into my own maven repo, so that won't be an issue any more.

**Comment by Votsh64** [comment]
It works under windows but not on jessie (pine64)

**Comment by DaMatrix** [comment]
as previously asked, what java version are you using? use the latest JDK 8 or it most likely will not compile.

**Comment by Votsh64** [comment]
JRE 8

**Comment by DaMatrix** [comment]
WHICH ONE? there are nearly 200 releases of java 8

**Comment by Votsh64** [comment]
java version "1.7.0_181"
OpenJDK Runtime Environment (IcedTea 2.6.14) (7u181-2.6.14-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.181-b01, mixed mode)

**Comment by Votsh64** [comment]
I can not change the version of java in the environment variable

**Comment by DaMatrix** [comment]
you're using java 7. you don't use an environment variable to change that, you need to physically uninstall java 7 and install java 8. try google next time.
