### ISSUE TITLE
Failed to load class "org.sl4fj.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by ghost** [DaMatrix/Pork2b2tBot#24]
Sorry for more issues, but after using the bot and getting disconnected every so often, I was unable to actually get into 2b2t. After restarting the bot, I noticed that the bot failed to load class "org.sl4fj.impl.StaticLoggerBinder". Could this have something to do with the disconnects? Thanks.
![image](https://user-images.githubusercontent.com/44863579/61256641-132f8c80-a7a0-11e9-8bb7-f9e600aae455.png)
[2019.07.16 07.55.58-debug.log](https://github.com/PorkStudios/Pork2b2tBot/files/3394636/2019.07.16.07.55.58-debug.log)

**Comment by DaMatrix** [comment]
that has nothing to do with the disconnects, no. the disconnect is because you wrote "stop" in the console (although actually pressing enter will disconnect you, regardless of what you type).
