### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by dannyc03** [DaMatrix/Pork2b2tBot#26]
Could you explain how to use the latest version, when I open the .jar, it's just a blank screen, open the config and I config it, butI can't connect and don't know what to put at a bind host, in short I'm asking, could you do a quick tutorial on how to use toobeetootee bot

**Comment by DaMatrix** [comment]
no

this is intended to be used by people who know what they're doing, if you can't figure it out yourself you shouldn't be using it
