### ISSUE TITLE
How can i use it

### ISSUE THREAD

**Issue by HelliosBey** [DaMatrix/Pork2b2tBot#33]
Im using Windows 7 and i could not use this thing. can u help me? And please explain it step by step.

**Comment by VADemon** [comment]
If you need this explained, it probably isn't for you...

start.sh file in the code files starts the proxy with this: `java -Xmx512M -jar <filename>.jar`

You need to open the console (commandline) first to type in that command and select the folder where your .jar is.

After it generates the config file, kill the process by pressing Ctrl+C, edit config and restart.

**Comment by HelliosBey** [comment]
so, i can't use this?

**Comment by HelliosBey** [comment]
Which .jar file ? I can't understand.

**Comment by DaMatrix** [comment]
https://github.com/PorkStudios/Pork2b2tBot/releases/latest

**Comment by HelliosBey** [comment]
Sources or other one?

**Comment by DaMatrix** [comment]
the one that isn't sources. i don't provide support for this software, if you can't figure out how to use it yourself you probably shouldn't be using it at all.

**Comment by HelliosBey** [comment]
I understand u. Bot last quesiton:
java.util.concurrent.ExecutionException: com.github.steveice10.mc.auth.exception.request.RequestException: Access Token can not be null or empty.
How can i fix it. Or what should i do

**Comment by HelliosBey** [comment]
Can u explain ?
