### ISSUE TITLE
How can i run index.html

### ISSUE THREAD

**Issue by ensgnnc** [DaMatrix/Pork2b2tBot#35]
I opened start.sh but index.html doesn't work ? What should i do?

**Comment by DaMatrix** [comment]
if you don't know how to use this, it isn't for you. i don't provide support for it

**Comment by ensgnnc** [comment]
I can wait on line with this. But i cant use index.html. I tried node main.js it didn't work. How can i run it.

**Comment by DaMatrix** [comment]
- `index.html` is not code, it's part of the web ui which really shouldn't be used
- `node main.js` won't work because this project is not written in javascript
- read my previous comment
