### ISSUE TITLE
Double chat

### ISSUE THREAD

**Issue by bitsofreedom** [DaMatrix/Pork2b2tBot#6]
All chat is doubled:

![image](https://user-images.githubusercontent.com/34915492/34740487-d4fcbb6e-f57f-11e7-823d-32772466f341.png)

  Not double in GUI:
![image](https://user-images.githubusercontent.com/34915492/34740520-f3cb0118-f57f-11e7-910f-065ad2f3526e.png)

**Comment by DaMatrix** [comment]
Unable to reproduce, and I've heard this is caused by a client glitch.

**Comment by novadoge** [comment]
Odd, I can reproduce, both on my mac and windows boxes..

https://i.imgur.com/7f4boMm.png

**Comment by novadoge** [comment]
bandaid solution for me was to remove

`listeners.put(ServerChatPacket.class, new ListenerChatPacket());`

from ListenerRegistry. Only drawback is it disables pretty much all chat functions (duh).

**Comment by novadoge** [comment]
Best fix for now is to remove

`client.session.send(new ServerChatPacket(legacyColorCodes));`

from ListenerChatPacket. Stops the double message thing and keeps chat functions.
